export const USER_REGISTER_DONE = "AUTH/USER_REGISTER_DONE"
export const USER_REGISTER_LOADING = "AUTH/USER_REGISTER_LOADING"
export const USER_REGISTER_FAILD = "AUTH/USER_REGISTER_FAILD"
//login
export const USER_LOGIN_DONE = "AUTH/USER_LOGIN_DONE";

// logout 
export const USER_LOGOUT = "AUTH/LOGOUT_USER"