export const LOADED = "ALL_BLOG_LOADED";
export const LOADING = "IS_LOADING";
export const FAILD = "IS_FAILD";

// SINGLE DATA ACTION TYPE
export const SINGLE_LOADED = "SINGLE_BLOG_LOADED";
export const SINGLE_LOADING = "SINGLE_LOADING";
export const SINGLE_FAILD = "SINGLE_FAILD";
// RELATED DATA ACTION TYPE
export const RELATED_LOADED = "RELATED_BLOG_LOADED";
export const RELATED_LOADING = "RELATED_LOADING";
export const RELATED_FAILD = "RELATED_FAILD";

// comment 
export const COMMENT_POST = "BLOG/COMMENT_POST";
export const COMMENT_POST_ERROR = "BLOG/COMMENT_POST_ERROR";
export const COMMENT_LOADING = "BLOG/LIKED_LOADING";
export const DELETE_COMMENT = "BLOG/DELETED_COMMENT"
export const DELETE_COMMENT_LOADING = "BLOG/DELETE_COMMENT_LOADING"
export const DELETE_COMMENT_ERROR = "BLOG/DELETE_COMMENT_ERROR"
export const EDIT_UPDATED = "BLOG/EDIT_UPDATED"
export const EDIT_UPDATED_LOADING = "BLOG/EDIT_UPDATED_LOADING"
export const EDIT_UPDATED_ERROR = "BLOG/EDIT_UPDATED_ERROR"
// like
export const LIKED = "BLOG/ISLIKED";
export const LIKED_ERROR = "BLOG/LIKED_ERROR";
export const LIKED_LOADING = "BLOG/LIKED_LOADING";


