export const AUTHOR_DATA_LOADED = "AUTHOR/AUTHOR_DATA_LOADED";
export const AUTHOR_DATA_LOADING = "AUTHOR/AUTHOR_DATA_LOADING";
export const AUTHOR_DATA_ERROR = "AUTHOR/AUTHOR_DATA_ERROR";
// author 
// Blog delete
export const AUTHOR_BLOG_DELETE = "AUTHOR/BLOG_DELETE";
export const AUTHOR_BLOG_DELETE_ERROR = "AUTHOR/BLOG_DELETE_ERROR";
export const AUTHOR_BLOG_DELETE_LOADING = "AUTHOR/BLOG_DELETE_LOADING";